#!/bin/sh /etc/rc.common

START=55

env_authorized_keys="authorized-ssh-keys"
path_authorized_keys="/tmp/authorized_keys"

boot() {
  if fw_printenv -n "$env_authorized_keys" > /dev/null 2>&1; then
    fw_printenv -n "$env_authorized_keys" | base64 -d | gzip -d > \
      "$path_authorized_keys"
  fi
}
