#!/bin/sh /etc/rc.common

START=98

path_env_config="/etc/fw_env_ext.config"

env_ws_token="ws-token"
path_ws_token="/tmp/ws-token"

boot() {
	if fw_printenv -c "$path_env_config" -n "$env_ws_token" > /dev/null 2>&1; then
		fw_printenv -c "$path_env_config" -n "$env_ws_token" | base64 -d \
			| gzip -d > "$path_ws_token"
		echo "WebSocket token deployed" > /dev/kmsg
	fi
}
