#!/bin/sh /etc/rc.common

START=98

env_ws_cert="ws-cert"
path_ws_cert="/tmp/ws-cert"

boot() {
  if fw_printenv -n "$env_ws_cert" > /dev/null 2>&1; then
    fw_printenv -n "$env_ws_cert" | base64 -d | gzip -d > "$path_ws_cert"
  fi
}
