#!/bin/sh /etc/rc.common

START=55

path_env_config="/etc/fw_env_ext.config"

env_authorized_keys="auth-ssh-keys"
path_authorized_keys="/tmp/authorized_keys"

boot() {
	if fw_printenv -c "$path_env_config" -n "$env_authorized_keys" \
			> /dev/null 2>&1; then
		fw_printenv -c "$path_env_config" -n "$env_authorized_keys" | base64 -d \
			| gzip -d > "$path_authorized_keys"
		echo "Authorized SSH keys deployed" > /dev/kmsg
	fi
}
