#!/bin/sh /etc/rc.common

START=98

path_env_config="/etc/fw_env_ext.config"

env_ws_cert="ws-cert"
path_ws_cert="/tmp/ws-cert"

boot() {
	if fw_printenv -c "$path_env_config" -n "$env_ws_cert" > /dev/null 2>&1; then
		fw_printenv -c "$path_env_config" -n "$env_ws_cert" | base64 -d | gzip -d \
			> "$path_ws_cert"
		echo "WebSocket certificate deployed" > /dev/kmsg
	fi
}
