#!/bin/sh /etc/rc.common

START=18

boot() {
  if [ "$(uci get wireless.ap.disabled)" != "1" ]; then
    if [ -n "$(uci get wireless.sta.ssid)" ]; then
      config-wifi-sta 1
    else
      config-wifi-ap 0
    fi
  fi
}
