#!/bin/sh /etc/rc.common

START=90

boot() {
	[ -d /usr ] || mkdir /usr
	for d in /tmp/vol/2/usr/*; do
		[ -d "$d" ] || continue
		base_d=$(basename "$d")
		[ -d "/usr/$base_d" ] || mkdir "/usr/$base_d"
		for f in "${d}/"*; do
			base_f=$(basename "$f")
			[ -e "/usr/${base_d}/${base_f}" ] || ln -s "$f" "/usr/${base_d}/${base_f}"
		done
	done
}
