#!/bin/sh

timeout=$(uci get wireless.ap.duration)

[ "$timeout" -gt 0 ] || exit 2

sleep "$timeout" && {
  if [ "$(uci get wireless.ap.disabled)" -eq 0 ]; then
    uci set wireless.ap.disabled=1
    wifi
  fi
}
