#!/bin/sh

cmd=$(basename "$0")
enabled="$1"
ssid="$2"
encryption="$3"
passwd="$4"

dialect=

case "$cmd" in
  config-wifi-ap)
    dialect=ap
    ;;
  config-wifi-sta)
    dialect=sta
    ;;
  *)
    dialect=
    ;;
esac

[ "$enabled" = "1" -o "$enabled" = "0" ] || {
	cat << EOF
usage: config-wifi-$dialect <enabled> [<ssid> <encryption> <password>]

enabled: 1, 0
encryption: psk, psk+aes, psk+tkip, psk+tkip+aes, psk2, psk2+aes, psk2+tkip, psk2+tkip+aes
EOF
	exit 2
}

. /lib/functions/wireless.sh

if [ "$enabled" = "1" ]; then
	uci set wireless.$dialect.disabled="0"
	case "$dialect" in
		ap)
			uci batch << EOF
set network.lan.proto=static
set wireless.sta.disabled=1
commit network
EOF
			;;
		sta)
			uci batch << EOF
set network.lan.proto=none
set wireless.ap.disabled=1
commit network
EOF
			;;
	esac
elif [ "$enabled" = "0" ]; then
	uci set wireless.$dialect.disabled="1"
fi

[ -n "$ssid" ] && uci set wireless.$dialect.ssid="$ssid"
[ -n "$passwd" ] && uci set wireless.$dialect.key="$(wireless_encrypt_passwd "$passwd")"
[ -n "$encryption" ] && uci set wireless.$dialect.encryption="$encryption"

uci commit wireless
