#!/bin/sh

usage() {
  cat << EOF
usage: factory-reset -y

This command will restore the default setup, resetting all custom settings and
removing all installed packages, logs, dumps, and temp files.
EOF
}

[ "$1" = "-y" ] || {
  usage
  exit 2
}

[ -x /etc/init.d/apcliled ] && /etc/init.d/apcliled stop

for c in j i h g f e d c b a; do
  [ -x /etc/init.d/custom-${c} ] && /etc/init.d/custom-${c} stop
done

led cyan blinking

if mountpoint -q /tmp/vol/2; then
  fuser -km /tmp/vol/2
fi

umount /dev/mmcblk0p2
mkfs.ext4 -Fq /dev/mmcblk0p2
rm -rf /tmp/vol/2
mkdir -p /tmp/vol/2
mount -t ext4 -o "data=journal,sync" /dev/mmcblk0p2 /tmp/vol/2

if mountpoint -q /tmp/vol/1 && mountpoint -q /tmp/vol/2; then
  tar -xzf /tmp/vol/1/extfs.tgz -C /tmp/vol/2
fi

mount_root
firstboot -y

led off
