#!/bin/sh

pid=$$
state=

ONLINE="online"
CONNECTED="connected"
OFFLINE="offline"
APENABLED="apenabled"

. /usr/share/libubox/jshn.sh

until false; do
  if ip -f inet address show wwan0 2>/dev/null | grep -qE '[0-9]{1,3}(\.[0-9]{1,3}){3}'; then
    current_state="$CONNECTED"
    if wget -O - -T 3 www.google.com; then
      current_state="$ONLINE"
    fi
  else
    if [ "$(ip address show wlan0 2>/dev/null | wc -l)" -gt 0 ]; then
      current_state="$APENABLED"
    else
      current_state="$OFFLINE"
    fi
  fi

  if [ "$current_state" != "$state" ]; then
    logger "wifiledd: WWAN is $current_state"
    case $current_state in
      $ONLINE)
        led green
        ;;
      $CONNECTED)
        led green blinking
        ;;
      $OFFLINE)
        led white
        ;;
      $APENABLED)
        led white blinking
        ;;
    esac

    state="$current_state"
  fi

  sleep 5
done
