#!/bin/sh

enabled="$1"
ssid="$2"
encryption="$3"
key="$4"

[ "$enabled" = "1" -o "$enabled" = "0" ] || {
	cat << EOF
usage: config-wifi-ap <enabled> [<ssid> <encryption> <password>]

enabled: 1, 0
encryption: psk, psk+aes, psk+tkip, psk+tkip+aes, psk2, psk2+aes, psk2+tkip, psk2+tkip+aes
EOF
	exit 2
}

. /usr/share/rt2860v2/encrypt.sh

if [ "$enabled" = "1" ]; then
	uci set wireless.ap.disabled="0"
elif [ "$enabled" = "0" ]; then
	uci set wireless.ap.disabled="1"
fi

[ -n "$ssid" ] && uci set wireless.ap.ssid="$ssid"
[ -n "$key" ] && uci set wireless.ap.key=$(get_encrypted_ap_key "$key")
[ -n "$encryption" ] && uci set wireless.ap.encryption="$encryption"

uci commit
