#!/bin/sh

[ "${ACTION}" = "released" -o "${ACTION}" = "timeout" ] || exit 21

logger "$BUTTON pressed for $SEEN seconds"

if [ $SEEN -ge 10 ]; then
	for f in $(ls /tmp/vol/2/lib/rc.button/$BUTTON/on-long-click.d); do
		[ -x "/tmp/vol/2/lib/rc.button/$BUTTON/on-long-click.d/$f" ] && \
				"/tmp/vol/2/lib/rc.button/$BUTTON/on-long-click.d/$f"
	done &

	sleep 10

	for f in $(ls /lib/rc.button/$BUTTON/on-long-click.d); do
		[ -x "/lib/rc.button/$BUTTON/on-long-click.d/$f" ] && \
				"/lib/rc.button/$BUTTON/on-long-click.d/$f"
	done
else
	for f in $(ls /tmp/vol/2/lib/rc.button/$BUTTON/on-click.d); do
		[ -x "/tmp/vol/2/lib/rc.button/$BUTTON/on-click.d/$f" ] && \
				"/tmp/vol/2/lib/rc.button/$BUTTON/on-click.d/$f"
	done &

	sleep 10

	for f in $(ls /lib/rc.button/$BUTTON/on-click.d); do
		[ -x "/lib/rc.button/$BUTTON/on-click.d/$f" ] && \
				"/lib/rc.button/$BUTTON/on-click.d/$f"
	done
fi
