#!/bin/sh

[ "${ACTION}" = "released" -o "${ACTION}" = "timeout" ] || exit 21

logger "$BUTTON pressed for $SEEN seconds"

if [ $SEEN -ge 10 ]; then
	for f in $(ls /lib/rc.button/$BUTTON/on-long-click.d); do
		"/lib/rc.button/$BUTTON/on-long-click.d/$f"
	done
else
	for f in $(ls /lib/rc.button/$BUTTON/on-click.d); do
		"/lib/rc.button/$BUTTON/on-click.d/$f"
	done
fi
