#!/bin/sh /etc/rc.common
# Copyright (C) 2016 Rosonix Technology, Inc.

START=11

boot() {
	wifiaddr=$(uci get wireless.ap.macaddr)

	if [ -n "$wifiaddr" ]; then
		insmod /lib/modules/$(uname -r)/rt2860v2_ap mac="$wifiaddr"
	else
		insmod /lib/modules/$(uname -r)/rt2860v2_ap
	fi
}
