#!/bin/sh

[ "${ACTION}" = "released" -o "${ACTION}" = "timeout" ] || exit 21

logger "$BUTTON pressed for $SEEN seconds"

click_folder="/lib/rc.button/${BUTTON}/on-click.d"
long_click_folder="/lib/rc.button/${BUTTON}/on-long-click.d"
ext_click_folder="/tmp/vol/2/lib/rc.button/${BUTTON}/on-click.d"
ext_long_click_folder="/tmp/vol/2/lib/rc.button/${BUTTON}/on-long-click.d"

if [ $SEEN -ge 10 ]; then
  ubus send key "{\"name\": \"$BUTTON\", \"action\": \"longClick\"}" &
  if [ -d "$long_click_folder" \
      -a -n "$(ls -A "$long_click_folder" 2>/dev/null || true)" ]; then
    for f in "${long_click_folder}/"*; do
      [ -x "$f" ] && "$f"
    done
  fi
else
  ubus send key "{\"name\": \"$BUTTON\", \"action\": \"click\"}" &
  if [ -d "$click_folder" \
      -a -n "$(ls -A "$click_folder" 2>/dev/null || true)" ]; then
    for f in "${click_folder}/"*; do
      [ -x "$f" ] && "$f"
    done
  fi
fi
