#!/bin/sh

[ "${ACTION}" = "released" -o "${ACTION}" = "timeout" ] || exit 21

. /lib/functions.sh

logger "$BUTTON pressed for $SEEN seconds"

if [ "$SEEN" -gt 10 ]; then
	for f in $(ls /lib/rc.button/on-long-click.d); do
		"/lib/rc.button/on-long-click.d/$f"
	done
else
	for f in $(ls /lib/rc.button/on-click.d); do
		"/lib/rc.button/on-click.d/$f"
	done
fi
