#!/bin/sh

[ -x /etc/init.d/apcliled ] && /etc/init.d/apcliled stop

wifi down

for c in j i h g f e d c b a; do
  [ -x /etc/init.d/custom-${c} ] && /etc/init.d/custom-${c} stop
done

led cyan blinking

if mountpoint -q /tmp/vol/2; then
  fuser -km /tmp/vol/2
fi

umount /dev/mmcblk0p2
mkfs.ext4 -Fq /dev/mmcblk0p2
rm -rf /tmp/vol/2
mkdir -p /tmp/vol/2
mount -t ext4 -o "data=journal,sync" /dev/mmcblk0p2 /tmp/vol/2

if mountpoint -q /tmp/vol/1 && mountpoint -q /tmp/vol/2; then
  if [ -d "/tmp/vol/1/ipks" \
      -a -n "$(ls -A /tmp/vol/1/ipks 2>/dev/null || true)" ]; then
    for f in /tmp/vol/1/ipks/*; do
      opkg install --nodeps -d ext "$f"
    done
  fi
  if [ -d "/tmp/vol/1/tarballs" \
      -a -n "$(ls -A /tmp/vol/1/tarballs 2>/dev/null || true)" ]; then
    for f in /tmp/vol/1/tarballs/*; do
      tar -xzf "$f" -C /tmp/vol/2
    done
  fi
fi

led off
