#!/bin/sh /etc/rc.common

START=20
STOP=90

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /sbin/seriald -b115200 -fh /dev/ttyS0
	procd_set_param respawn
	procd_close_instance
}
