#!/bin/sh

. /usr/share/rt2860v2/utils.sh

iface="$1"
ssid="$2"
key="$3"

MAX_INTERVAL=60
interval=0

[ -z "$iface" -o -z "$ssid" ] && exit 1

while true; do
	if ! iwconfig "$iface" | grep -Fq 'Not-Associated'; then
		# $iface has connected to an AP
		interval=0
		sleep $MAX_INTERVAL
		continue
	fi

	# Begin to connect to the AP

	ifconfig $iface down

	iwpriv $iface set ApCliEnable="0"

	local result=$(site_survey "$iface")

	local channel=$(echo "$result" | parse_channel_of_specific_ssid_from_site_survey_result "$ssid")

	[ -z "$channel" ] && {
		interval=$(( interval + 1 ))
		[ $interval -gt $MAX_INTERVAL ] && internal=$MAX_INTERVAL
		sleep $interval
		continue
	}

	interval=0

	local encryption=$(echo "$result" | parse_encryption_of_specific_ssid_from_site_survey_result "$ssid")

	local authmode enctype

	case "$encryption" in
		psk2*)
			authmode="WPA2PSK"
			;;
		psk*)
			authmode="WPAPSK"
			;;
		none)
			authmode="NONE"
			;;
	esac

	case "$encryption" in
		*aes*)
			enctype="AES"
			;;
		*tkip*)
			enctype="TKIP"
			;;
	esac

	iwpriv $iface set Channel="$channel"
	iwpriv $iface set ApCliSsid="$ssid"
	iwpriv $iface set ApCliAuthMode="$authmode"
	if [ "$authmode" != "NONE" ]; then
		iwpriv $iface set ApCliEncrypType="$enctype"
		iwpriv $iface set ApCliWPAPSK="$key"
	fi
	iwpriv $iface set ApCliEnable="1"

	ifconfig $iface up

	# Wait for station to connect to the AP
	for i in $(seq $MAX_INTERVAL); do
		if ! iwconfig apcli0 | grep -q 'Not-Associated'; then
			break
		fi
		sleep 1
	done
done
