#!/bin/sh

. /usr/share/libubox/jshn.sh
. /usr/share/rt2860v2/utils.sh

simplified_ap_list() {
  local aplist="$1"
  echo "$aplist" | while read -r line; do
    echo "$(echo "$line" | cut -b 5-36) $(echo "$line" | cut -b 58-83)"
  done
}

aplist=$(site_survey $(uci get wireless.sta.ifname))
aplist=$(simplified_ap_list "$aplist" | sort -f | uniq -w 55)

json_init
json_add_array "result"

while [ -n "$aplist" ]; do
  local line=$(echo "$aplist" | head -n 1)
  aplist=$(echo "$aplist" | tail -n '+2')
  ssid=$(echo "$line" | cut -b 1-32 | sed -e 's/[[:space:]]*$//')
  security=$(echo "$line" | cut -b 34-55 | sed -e 's/[[:space:]]*$//')
  strength=$(echo "$line" | cut -b 57-59 | sed -e 's/[[:space:]]*$//')
  local encryption
  case "$security" in
  WPA1PSKWPA2PSK*)
    encryption="psk-mixed"
    ;;
  WPA2PSK*)
    encryption="psk2"
    ;;
  WPAPSK*|WPA1PSK*)
    encryption="psk"
    ;;
  NONE*)
    ;;
  esac
  [ -n "$encryption" ] || continue
  case "$security" in
  *TKIPAES)
    encryption="${encryption}+tkip+aes"
    ;;
  *TKIP)
    encryption="${encryption}+tkip"
    ;;
  *AES)
    encryption="${encryption}+aes"
    ;;
  esac
  json_add_object
  json_add_string "ssid" "$ssid"
  json_add_string "encryption" "$encryption"
  json_add_string "strength" "$strength"
  json_close_object
done

json_close_array
json_dump
