#!/bin/sh /etc/rc.common
# Copyright (C) 2016 Rosonix Technology, Inc.

START=80
STOP=20

USE_PROCD=1
PROG="/sbin/apcliledd"

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
}
