#!/bin/sh /etc/rc.common
# Copyright (C) 2016 Rosonix Technology, Inc.

START=98

boot() {
	# Mount eMMC partitions
	[ -b "/dev/mmcblk0p1" ] && {
		mkdir -p /tmp/vol/1
		mount -t ext4 -r /dev/mmcblk0p1 /tmp/vol/1
	}
	[ -b "/dev/mmcblk0p2" ] && {
		fsck.ext4 -pfc /dev/mmcblk0p2
		mkdir -p /tmp/vol/2
		mount -t ext4 -o data=journal,sync /dev/mmcblk0p2 /tmp/vol/2
	}

	# Install symlinks
	[ -d /usr ] || mkdir /usr
	for d in /tmp/vol/2/usr/*; do
		[ -d "$d" ] || continue
		base_d=$(basename "$d")
		[ -d "/usr/$base_d" ] || mkdir "/usr/$base_d"
		for f in "${d}/"*; do
			base_f=$(basename "$f")
			[ -e "/usr/${base_d}/${base_f}" ] || ln -s "$f" "/usr/${base_d}/${base_f}"
		done
	done
}
