#!/bin/sh /etc/rc.common
# Copyright (C) 2016 Rosonix Technology, Inc.

START=10

boot() {
	ethaddr=$(fw_printenv ethaddr | sed 's/ethaddr=//;s/\"//g')

	[ -z "$ethaddr" ] && return

	n=$(echo 0x$ethaddr | sed 's/://g')

	# For module, the MAC for Wi-Fi (ra0) should be "n % 2 = 0"
	while [ "$(( n % 2 ))" != "0" ]; do
	  n=$(( n + 1 ))
	done

	wifiaddr=$(printf "%012X" $n | sed 's/\(..\)\(..\)\(..\)\(..\)\(..\)\(..\)/\1:\2:\3:\4:\5:\6/' | tr [:upper:] [:lower:])

	if [ "$(uci get wireless.ap.macaddr)" != "$wifiaddr" ]; then
		uci set wireless.ap.macaddr="$wifiaddr"
		uci set wireless.ap.ssid="I2CD $(echo -n $wifiaddr | sed 's/://g' | tail -c 6 | tr [:lower:] [:upper:])"
		local keykey=$(echo -n "$wifiaddr" | awk -F ":" '{print $4""$5""$6 }' | tr [:lower:] [:upper:])
		local realkey=$(echo -n $wifiaddr | sed 's/://g' | tail -c 8 | tr [:lower:] [:upper:])
		local key=$(echo -n "$realkey" | openssl aes-256-cbc -k "$keykey" | base64)
		uci set wireless.ap.key="$key"
		uci set wireless.ap.encryption=psk2
		uci commit
	fi
}
