#!/bin/sh /etc/rc.common
# Copyright (C) 2016 Rosonix Technology, Inc.

START=10

boot() {
	ethaddr=$(fw_printenv ethaddr | sed 's/ethaddr=//;s/\"//g')

	[ -z "$ethaddr" ] && return

	if [ "$(uci get network.lan0.macaddr)" != "$ethaddr" ]; then
		uci set network.lan0.macaddr="$ethaddr"
		uci commit
	fi
}
